#!/usr/bin/env python3
"""Extract Joe's Calibrage's translatable strings into i18n/joes-calibrage.pot.

Why not xgettext: `--keyword=T` only sees strings inside T(...), which is
exactly the universe here -- Thing-File wraps visible literals by hand at the
call site, and anything not wrapped is deliberately untranslated (paths, log
messages, config keys). A missed wrap shows up as English on the panel and in
review, not as a silently-shrinking key universe.

Usage:
    tools/i18n-extract.py                 # rewrite i18n/joes-calibrage.pot
    tools/i18n-extract.py --check         # fail if the committed .pot is stale
    tools/i18n-extract.py --check --po i18n/zh_CN.po
                                          # ...and validate the .po: orphan
                                          # keys, duplicates, incompatible
                                          # placeholders, coverage gate
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POT = ROOT / "i18n" / "joes-calibrage.pot"

# Sources with UI text. The multifont/utf8/render plumbing draws data, not
# chrome; sdl_gfx is vendored third party.
SOURCE_GLOBS = ["src/*.c", "src/*.h"]
EXCLUDE_PARTS = ()

FUNNELS = ["T"]

# A run of adjacent string literals -- C++ concatenates "a" "b" into one
# string. Every extraction site must treat the run as ONE key or the runtime
# key never matches.
STR = r'"(?:[^"\\]|\\.)*"'
RUN = re.compile(STR + r"(?:\s*" + STR + r")*")


def run_to_text(run: str) -> str:
    return "".join(m.group(1) for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', run))


def c_unescape(s: str) -> str:
    return (s.replace(r"\n", "\n").replace(r"\t", "\t")
             .replace(r"\"", '"').replace(r"\\", "\\"))


def strip_comments(src: str) -> str:
    """Drop comments so a commented-out call is not extracted. String contents
    survive (the scanner tracks quoting)."""
    out = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c == '"':
            j = i + 1
            while j < n and (src[j] != '"' or src[j - 1] == "\\"):
                j += 1
            out.append(src[i:j + 1]); i = j + 1
        elif src.startswith("//", i):
            j = src.find("\n", i)
            i = n if j < 0 else j
        elif src.startswith("/*", i):
            j = src.find("*/", i + 2)
            i = n if j < 0 else j + 2
        else:
            out.append(c); i += 1
    return "".join(out)


def call_spans(src: str, name: str):
    """Yield the text between the parentheses of each `name(...)` call."""
    for m in re.finditer(r"\b" + re.escape(name) + r"\s*\(", src):
        depth, j = 1, m.end()
        while j < len(src) and depth:
            c = src[j]
            if c == '"':
                j += 1
                while j < len(src) and (src[j] != '"' or src[j - 1] == "\\"):
                    j += 1
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
            j += 1
        yield src[m.end():j - 1]


def extract():
    keys = {}

    def add(lit, where):
        text = c_unescape(lit)
        if not text or text == "%s":
            return
        keys.setdefault(text, where)

    files = []
    for pattern in SOURCE_GLOBS:
        files.extend(ROOT.glob(pattern))
    for f in sorted(set(files)):
        rel = f.relative_to(ROOT).as_posix()
        if any(rel.startswith(part) for part in EXCLUDE_PARTS):
            continue
        src = strip_comments(f.read_text(encoding="utf-8", errors="replace"))
        for fn in FUNNELS:
            for span in call_spans(src, fn):
                for m in RUN.finditer(span):
                    add(run_to_text(m.group(0)), rel)
    return keys


def write_pot(keys, path: Path):
    lines = [
        "# Joe's Calibrage UI strings. GENERATED by tools/i18n-extract.py -- do not",
        "# edit; regenerate with `make i18n-pot`. The English string is the key,",
        '# and a context prefix ("verb|Open") is part of the key.',
        'msgid ""',
        'msgstr "Content-Type: text/plain; charset=UTF-8\\n"',
        "",
    ]
    for key in sorted(keys):
        esc = key.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        lines.append(f"#: {keys[key]}")
        lines.append(f'msgid "{esc}"')
        lines.append('msgstr ""')
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def pot_keys(path: Path):
    out = set()
    for m in re.finditer(r'^msgid "((?:[^"\\]|\\.)*)"', path.read_text(encoding="utf-8"), re.M):
        if m.group(1):
            out.add(c_unescape(m.group(1)))
    return out


def po_entries(path: Path):
    """[(key, msgstr, fuzzy)] preserving every entry (duplicates included).
    Handles multi-line msgid/msgstr continuation strings and `#, fuzzy`."""
    entries = []
    fuzzy = False          # marker seen before the current entry
    state = "idle"         # idle | msgid | msgstr
    key, val = "", ""
    STRCONT = r'"((?:[^"\\]|\\.)*)"'

    def flush():
        nonlocal key, val, state, fuzzy
        if state == "msgstr" and key != "":
            entries.append((key, val, fuzzy))
        key, val = "", ""
        state = "idle"

    text = path.read_text(encoding="utf-8")
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            flush()
            fuzzy = False
            continue
        if s.startswith("#"):
            if s.startswith("#,") and "fuzzy" in {flag.strip() for flag in s[2:].split(",")}:
                fuzzy = True
            continue
        if s.startswith("msgid "):
            flush()
            key = "".join(c_unescape(m) for m in re.findall(STRCONT, s[len("msgid "):]))
            state = "msgid"
            continue
        if s.startswith("msgstr "):
            val = "".join(c_unescape(m) for m in re.findall(STRCONT, s[len("msgstr "):]))
            state = "msgstr"
            continue
        m = re.fullmatch(STRCONT, s)
        if m and state == "msgid":
            key += c_unescape(m.group(1))
        elif m and state == "msgstr":
            val += c_unescape(m.group(1))
    flush()
    return entries


def fmt_sig(s: str):
    """printf-conversion fingerprint: (count, modifiers+conversions string).
    Mirrors the runtime check in src/i18n.cpp, which refuses a translation
    whose conversions do not match its key's."""
    mods = []
    n = 0
    i = 0
    conv = "-+ #0123456789.*'"
    length = "hlLqjzt"
    while i < len(s):
        if s[i] != "%":
            i += 1
            continue
        i += 1
        if i < len(s) and s[i] == "%":
            i += 1
            continue
        if i >= len(s):
            return None
        while i < len(s) and s[i] in conv:
            i += 1
        mod = ""
        while i < len(s) and s[i] in length:
            mod += s[i]
            i += 1
        if i >= len(s):
            return None
        mods.append(mod + s[i])
        i += 1
        n += 1
    return n, "".join(mods)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if i18n/joes-calibrage.pot is stale instead of rewriting it")
    ap.add_argument("--po", nargs="*", default=[],
                    help="translation files to validate against the extracted set")
    ap.add_argument("--gate", type=int, default=90,
                    help="minimum reviewed coverage percent for --po (default 90)")
    args = ap.parse_args()

    keys = extract()
    print(f"extracted {len(keys)} keys")

    rc = 0
    if args.check:
        if not POT.exists():
            print(f"FAIL: {POT} does not exist; run tools/i18n-extract.py", file=sys.stderr)
            return 1
        committed = pot_keys(POT)
        fresh = set(keys)
        missing = sorted(fresh - committed)
        stale = sorted(committed - fresh)
        if missing or stale:
            for k in missing[:20]:
                print(f"  not in committed .pot: {k!r}", file=sys.stderr)
            if len(missing) > 20:
                print(f"  ... and {len(missing) - 20} more", file=sys.stderr)
            for k in stale[:20]:
                print(f"  in .pot but no longer in code: {k!r}", file=sys.stderr)
            if len(stale) > 20:
                print(f"  ... and {len(stale) - 20} more", file=sys.stderr)
            print("FAIL: i18n/joes-calibrage.pot is stale; run `make i18n-pot` and commit it",
                  file=sys.stderr)
            rc = 1
        else:
            print("i18n/joes-calibrage.pot is current")
    else:
        write_pot(keys, POT)
        print(f"wrote {POT.relative_to(ROOT)}")

    universe = set(keys)
    for po in args.po:
        p = Path(po)
        if not p.exists():
            continue
        entries = po_entries(p)
        seen = {}
        for k, v, f in entries:
            if k in seen:
                print(f"FAIL: {p.name}: duplicate key: {k!r}", file=sys.stderr)
                rc = 1
            seen[k] = (v, f)
        orphans = sorted(set(seen) - universe)
        if orphans:
            for k in orphans[:20]:
                print(f"  {p.name}: key not in the code: {k!r}", file=sys.stderr)
            print(f"FAIL: {p.name} has {len(orphans)} orphan key(s) -- an English "
                  "string was probably renamed; update the translation",
                  file=sys.stderr)
            rc = 1
        bad_fmt = 0
        for k, (v, f) in seen.items():
            if not v or k not in universe:
                continue
            ka, va = fmt_sig(k), fmt_sig(v)
            if ka is None or va is None or ka != va:
                print(f"  {p.name}: placeholder mismatch: {k!r} -> {v!r}",
                      file=sys.stderr)
                bad_fmt += 1
        if bad_fmt:
            print(f"FAIL: {p.name}: {bad_fmt} incompatible placeholder signature(s)",
                  file=sys.stderr)
            rc = 1
        reviewed = sum(1 for k in universe
                       if k in seen and seen[k][0] and not seen[k][1])
        pct = reviewed * 100 // max(1, len(universe))
        print(f"{p.name}: {reviewed}/{len(universe)} reviewed "
              f"({pct}%, gate {args.gate}%)")
        if pct < args.gate:
            print(f"FAIL: {p.name}: reviewed coverage {pct}% is below the "
                  f"{args.gate}% release gate", file=sys.stderr)
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
